Arguments don't have method 'join'
In yate 0.0.71 writing `module name` without apostrophes raises an error during compilation:
```
TypeError: Object #<Object> has no method 'join'
```

Instead of
```
Error: ERROR: Expected: ", '
at (8, 1) in /home/lunatik/Desktop/pfront/lib-header/header/header.yate:
...
```